name: GUILLERMOSANCHIDRIAN
favicon: null
layout_spectrum: 0.60893140360713
typography_spectrum: 0.9327950493898243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.28168302471749485
  lightness: 0.8973819287493825
  saturation: 0.6475033918395638
  rhythmicContrast: 0.5178200367372483
purpose: []
